/*
 * Copyright 2010-2020 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib")
@TestDataPath("$PROJECT_ROOT")
public class FirDiagnosticWithStdLibTestGenerated extends AbstractFirDiagnosticWithStdLibTest {
    @Test
    @TestMetadata("addAllOnJavaCollection.kt")
    public void testAddAllOnJavaCollection() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/addAllOnJavaCollection.kt");
    }

    @Test
    public void testAllFilesPresentInResolveWithStdlib() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("arrayFilterCapturedType.kt")
    public void testArrayFilterCapturedType() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/arrayFilterCapturedType.kt");
    }

    @Test
    @TestMetadata("arrayFirstOrNull.kt")
    public void testArrayFirstOrNull() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/arrayFirstOrNull.kt");
    }

    @Test
    @TestMetadata("arrayInLocal.kt")
    public void testArrayInLocal() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/arrayInLocal.kt");
    }

    @Test
    @TestMetadata("backingField.kt")
    public void testBackingField() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/backingField.kt");
    }

    @Test
    @TestMetadata("classLiteralForParameter.kt")
    public void testClassLiteralForParameter() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/classLiteralForParameter.kt");
    }

    @Test
    @TestMetadata("cloneArray.kt")
    public void testCloneArray() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/cloneArray.kt");
    }

    @Test
    @TestMetadata("companionLoad.kt")
    public void testCompanionLoad() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/companionLoad.kt");
    }

    @Test
    @TestMetadata("complexPostponedCfg.kt")
    public void testComplexPostponedCfg() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/complexPostponedCfg.kt");
    }

    @Test
    @TestMetadata("components.kt")
    public void testComponents() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/components.kt");
    }

    @Test
    @TestMetadata("concurrent.kt")
    public void testConcurrent() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/concurrent.kt");
    }

    @Test
    @TestMetadata("concurrentMapOfAliases.kt")
    public void testConcurrentMapOfAliases() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/concurrentMapOfAliases.kt");
    }

    @Test
    @TestMetadata("emptyArray.kt")
    public void testEmptyArray() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/emptyArray.kt");
    }

    @Test
    @TestMetadata("enumValuesDeserialized.kt")
    public void testEnumValuesDeserialized() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/enumValuesDeserialized.kt");
    }

    @Test
    @TestMetadata("exception.kt")
    public void testException() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/exception.kt");
    }

    @Test
    @TestMetadata("factoryFunctionOverloads.kt")
    public void testFactoryFunctionOverloads() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/factoryFunctionOverloads.kt");
    }

    @Test
    @TestMetadata("fillInStackTrace.kt")
    public void testFillInStackTrace() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/fillInStackTrace.kt");
    }

    @Test
    @TestMetadata("functionAndFunctionN.kt")
    public void testFunctionAndFunctionN() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/functionAndFunctionN.kt");
    }

    @Test
    @TestMetadata("functionX.kt")
    public void testFunctionX() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/functionX.kt");
    }

    @Test
    @TestMetadata("getOnKProperty.kt")
    public void testGetOnKProperty() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/getOnKProperty.kt");
    }

    @Test
    @TestMetadata("getOrPutAmbiguity.kt")
    public void testGetOrPutAmbiguity() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/getOrPutAmbiguity.kt");
    }

    @Test
    @TestMetadata("hashMapTypeAlias.kt")
    public void testHashMapTypeAlias() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/hashMapTypeAlias.kt");
    }

    @Test
    @TestMetadata("hashSet.kt")
    public void testHashSet() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/hashSet.kt");
    }

    @Test
    @TestMetadata("hashTableWithForEach.kt")
    public void testHashTableWithForEach() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/hashTableWithForEach.kt");
    }

    @Test
    @TestMetadata("helloWorld.kt")
    public void testHelloWorld() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/helloWorld.kt");
    }

    @Test
    @TestMetadata("implicitReceiverOrder.kt")
    public void testImplicitReceiverOrder() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/implicitReceiverOrder.kt");
    }

    @Test
    @TestMetadata("inapplicableRemoveAll.kt")
    public void testInapplicableRemoveAll() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inapplicableRemoveAll.kt");
    }

    @Test
    @TestMetadata("javaEnumSynthetic.kt")
    public void testJavaEnumSynthetic() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/javaEnumSynthetic.kt");
    }

    @Test
    @TestMetadata("javaLangComparator.kt")
    public void testJavaLangComparator() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/javaLangComparator.kt");
    }

    @Test
    @TestMetadata("kotlinComparatorAlias.kt")
    public void testKotlinComparatorAlias() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/kotlinComparatorAlias.kt");
    }

    @Test
    @TestMetadata("listPlusAssign.kt")
    public void testListPlusAssign() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/listPlusAssign.kt");
    }

    @Test
    @TestMetadata("lowPriorityInResolution.kt")
    public void testLowPriorityInResolution() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/lowPriorityInResolution.kt");
    }

    @Test
    @TestMetadata("mapList.kt")
    public void testMapList() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/mapList.kt");
    }

    @Test
    @TestMetadata("multipleImplicitReceivers.kt")
    public void testMultipleImplicitReceivers() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/multipleImplicitReceivers.kt");
    }

    @Test
    @TestMetadata("noneWithForEach.kt")
    public void testNoneWithForEach() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/noneWithForEach.kt");
    }

    @Test
    @TestMetadata("nullableTypeParameter.kt")
    public void testNullableTypeParameter() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/nullableTypeParameter.kt");
    }

    @Test
    @TestMetadata("plusAssignNullable.kt")
    public void testPlusAssignNullable() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/plusAssignNullable.kt");
    }

    @Test
    @TestMetadata("problems.kt")
    public void testProblems() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems.kt");
    }

    @Test
    @TestMetadata("rangeTo.kt")
    public void testRangeTo() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/rangeTo.kt");
    }

    @Test
    @TestMetadata("recursiveBug.kt")
    public void testRecursiveBug() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/recursiveBug.kt");
    }

    @Test
    @TestMetadata("reflectionClass.kt")
    public void testReflectionClass() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/reflectionClass.kt");
    }

    @Test
    @TestMetadata("removeIf.kt")
    public void testRemoveIf() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/removeIf.kt");
    }

    @Test
    @TestMetadata("removeOnAbstractMap.kt")
    public void testRemoveOnAbstractMap() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/removeOnAbstractMap.kt");
    }

    @Test
    @TestMetadata("runOnIntegerLiteral.kt")
    public void testRunOnIntegerLiteral() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/runOnIntegerLiteral.kt");
    }

    @Test
    @TestMetadata("samForComparator.kt")
    public void testSamForComparator() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/samForComparator.kt");
    }

    @Test
    @TestMetadata("simpleLazy.kt")
    public void testSimpleLazy() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/simpleLazy.kt");
    }

    @Test
    @TestMetadata("stringConstructors.kt")
    public void testStringConstructors() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/stringConstructors.kt");
    }

    @Test
    @TestMetadata("toSortedMapWithComparator.kt")
    public void testToSortedMapWithComparator() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/toSortedMapWithComparator.kt");
    }

    @Test
    @TestMetadata("topLevelResolve.kt")
    public void testTopLevelResolve() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/topLevelResolve.kt");
    }

    @Test
    @TestMetadata("typeAliasDeserialization.kt")
    public void testTypeAliasDeserialization() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/typeAliasDeserialization.kt");
    }

    @Test
    @TestMetadata("typeAliasWithForEach.kt")
    public void testTypeAliasWithForEach() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/typeAliasWithForEach.kt");
    }

    @Test
    @TestMetadata("typeParameterDerived.kt")
    public void testTypeParameterDerived() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/typeParameterDerived.kt");
    }

    @Test
    @TestMetadata("unaryOperators.kt")
    public void testUnaryOperators() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/unaryOperators.kt");
    }

    @Test
    @TestMetadata("whenAsLambdaReturnStatement.kt")
    public void testWhenAsLambdaReturnStatement() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/whenAsLambdaReturnStatement.kt");
    }

    @Test
    @TestMetadata("withInInitializer.kt")
    public void testWithInInitializer() throws Exception {
        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/withInInitializer.kt");
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences")
    @TestDataPath("$PROJECT_ROOT")
    public class CallableReferences extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInCallableReferences() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("beyoundCalls.kt")
        public void testBeyoundCalls() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/beyoundCalls.kt");
        }

        @Test
        @TestMetadata("coercionToUnit.kt")
        public void testCoercionToUnit() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/coercionToUnit.kt");
        }

        @Test
        @TestMetadata("companions.kt")
        public void testCompanions() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/companions.kt");
        }

        @Test
        @TestMetadata("constructors.kt")
        public void testConstructors() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/constructors.kt");
        }

        @Test
        @TestMetadata("differentLevels.kt")
        public void testDifferentLevels() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/differentLevels.kt");
        }

        @Test
        @TestMetadata("extensionReceiverInference.kt")
        public void testExtensionReceiverInference() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/extensionReceiverInference.kt");
        }

        @Test
        @TestMetadata("genericInReceiver.kt")
        public void testGenericInReceiver() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/genericInReceiver.kt");
        }

        @Test
        @TestMetadata("ifWithCR.kt")
        public void testIfWithCR() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/ifWithCR.kt");
        }

        @Test
        @TestMetadata("implicitTypes.kt")
        public void testImplicitTypes() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/implicitTypes.kt");
        }

        @Test
        @TestMetadata("inferenceFromCallableReferenceType.kt")
        public void testInferenceFromCallableReferenceType() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/inferenceFromCallableReferenceType.kt");
        }

        @Test
        @TestMetadata("inferenceFromExpectedType.kt")
        public void testInferenceFromExpectedType() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/inferenceFromExpectedType.kt");
        }

        @Test
        @TestMetadata("javaStatic.kt")
        public void testJavaStatic() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/javaStatic.kt");
        }

        @Test
        @TestMetadata("manyCandidatesInference.kt")
        public void testManyCandidatesInference() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/manyCandidatesInference.kt");
        }

        @Test
        @TestMetadata("manyInnerCandidates.kt")
        public void testManyInnerCandidates() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/manyInnerCandidates.kt");
        }

        @Test
        @TestMetadata("manyInnerManyOuterCandidates.kt")
        public void testManyInnerManyOuterCandidates() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/manyInnerManyOuterCandidates.kt");
        }

        @Test
        @TestMetadata("manyInnermanyOuterCandidatesAmbiguity.kt")
        public void testManyInnermanyOuterCandidatesAmbiguity() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/manyInnermanyOuterCandidatesAmbiguity.kt");
        }

        @Test
        @TestMetadata("manyOuterCandidates.kt")
        public void testManyOuterCandidates() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/manyOuterCandidates.kt");
        }

        @Test
        @TestMetadata("properties.kt")
        public void testProperties() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/properties.kt");
        }

        @Test
        @TestMetadata("sam.kt")
        public void testSam() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/sam.kt");
        }

        @Test
        @TestMetadata("simpleClassReceiver.kt")
        public void testSimpleClassReceiver() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/simpleClassReceiver.kt");
        }

        @Test
        @TestMetadata("simpleExpressionReceiver.kt")
        public void testSimpleExpressionReceiver() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/simpleExpressionReceiver.kt");
        }

        @Test
        @TestMetadata("simpleNoReceiver.kt")
        public void testSimpleNoReceiver() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/simpleNoReceiver.kt");
        }

        @Test
        @TestMetadata("varProperties.kt")
        public void testVarProperties() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/varProperties.kt");
        }

        @Nested
        @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests")
        @TestDataPath("$PROJECT_ROOT")
        public class FromBasicDiagnosticTests extends AbstractFirDiagnosticWithStdLibTest {
            @Test
            public void testAllFilesPresentInFromBasicDiagnosticTests() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
            }

            @Test
            @TestMetadata("ambiguityWhenNoApplicableCallableReferenceCandidate.kt")
            public void testAmbiguityWhenNoApplicableCallableReferenceCandidate() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/ambiguityWhenNoApplicableCallableReferenceCandidate.kt");
            }

            @Test
            @TestMetadata("applicableCallableReferenceFromDistantScope.kt")
            public void testApplicableCallableReferenceFromDistantScope() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/applicableCallableReferenceFromDistantScope.kt");
            }

            @Test
            @TestMetadata("chooseCallableReferenceDependingOnInferredReceiver.kt")
            public void testChooseCallableReferenceDependingOnInferredReceiver() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/chooseCallableReferenceDependingOnInferredReceiver.kt");
            }

            @Test
            @TestMetadata("commonSupertypeFromReturnTypesOfCallableReference.kt")
            public void testCommonSupertypeFromReturnTypesOfCallableReference() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/commonSupertypeFromReturnTypesOfCallableReference.kt");
            }

            @Test
            @TestMetadata("eagerAndPostponedCallableReferences.kt")
            public void testEagerAndPostponedCallableReferences() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/eagerAndPostponedCallableReferences.kt");
            }

            @Test
            @TestMetadata("eagerResolveOfSingleCallableReference.kt")
            public void testEagerResolveOfSingleCallableReference() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/eagerResolveOfSingleCallableReference.kt");
            }

            @Test
            @TestMetadata("moreSpecificAmbiguousExtensions.kt")
            public void testMoreSpecificAmbiguousExtensions() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/moreSpecificAmbiguousExtensions.kt");
            }

            @Test
            @TestMetadata("multipleOutersAndMultipleCallableReferences.kt")
            public void testMultipleOutersAndMultipleCallableReferences() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/multipleOutersAndMultipleCallableReferences.kt");
            }

            @Test
            @TestMetadata("noAmbiguityBetweenTopLevelAndMemberProperty.kt")
            public void testNoAmbiguityBetweenTopLevelAndMemberProperty() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/noAmbiguityBetweenTopLevelAndMemberProperty.kt");
            }

            @Test
            @TestMetadata("overloadsBound.kt")
            public void testOverloadsBound() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/overloadsBound.kt");
            }

            @Test
            @TestMetadata("postponedResolveOfManyCallableReference.kt")
            public void testPostponedResolveOfManyCallableReference() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/postponedResolveOfManyCallableReference.kt");
            }

            @Test
            @TestMetadata("resolveCallableReferencesAfterAllSimpleArguments.kt")
            public void testResolveCallableReferencesAfterAllSimpleArguments() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/resolveCallableReferencesAfterAllSimpleArguments.kt");
            }

            @Test
            @TestMetadata("withGenericFun.kt")
            public void testWithGenericFun() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/callableReferences/fromBasicDiagnosticTests/withGenericFun.kt");
            }
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts")
    @TestDataPath("$PROJECT_ROOT")
    public class Contracts extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInContracts() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Nested
        @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromLibrary")
        @TestDataPath("$PROJECT_ROOT")
        public class FromLibrary extends AbstractFirDiagnosticWithStdLibTest {
            @Test
            public void testAllFilesPresentInFromLibrary() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromLibrary"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
            }

            @Test
            @TestMetadata("callsInPlace.kt")
            public void testCallsInPlace() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromLibrary/callsInPlace.kt");
            }

            @Test
            @TestMetadata("conditionalEffects.kt")
            public void testConditionalEffects() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromLibrary/conditionalEffects.kt");
            }

            @Test
            @TestMetadata("notIsNullOrEmpty.kt")
            public void testNotIsNullOrEmpty() throws Exception {
                runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromLibrary/notIsNullOrEmpty.kt");
            }
        }

        @Nested
        @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource")
        @TestDataPath("$PROJECT_ROOT")
        public class FromSource extends AbstractFirDiagnosticWithStdLibTest {
            @Test
            public void testAllFilesPresentInFromSource() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
            }

            @Nested
            @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad")
            @TestDataPath("$PROJECT_ROOT")
            public class Bad extends AbstractFirDiagnosticWithStdLibTest {
                @Test
                public void testAllFilesPresentInBad() throws Exception {
                    KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                }

                @Nested
                @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/callsInPlace")
                @TestDataPath("$PROJECT_ROOT")
                public class CallsInPlace extends AbstractFirDiagnosticWithStdLibTest {
                    @Test
                    public void testAllFilesPresentInCallsInPlace() throws Exception {
                        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/callsInPlace"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                    }

                    @Test
                    @TestMetadata("inAnonymousObject.kt")
                    public void testInAnonymousObject() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/callsInPlace/inAnonymousObject.kt");
                    }

                    @Test
                    @TestMetadata("inLocalClass.kt")
                    public void testInLocalClass() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/callsInPlace/inLocalClass.kt");
                    }

                    @Test
                    @TestMetadata("inLocalFunction.kt")
                    public void testInLocalFunction() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/callsInPlace/inLocalFunction.kt");
                    }

                    @Test
                    @TestMetadata("toLocalVariables.kt")
                    public void testToLocalVariables() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/callsInPlace/toLocalVariables.kt");
                    }
                }

                @Nested
                @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/returnsImplies")
                @TestDataPath("$PROJECT_ROOT")
                public class ReturnsImplies extends AbstractFirDiagnosticWithStdLibTest {
                    @Test
                    public void testAllFilesPresentInReturnsImplies() throws Exception {
                        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/returnsImplies"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                    }

                    @Test
                    @TestMetadata("notNull.kt")
                    public void testNotNull() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/returnsImplies/notNull.kt");
                    }

                    @Test
                    @TestMetadata("propertyGetter.kt")
                    public void testPropertyGetter() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/returnsImplies/propertyGetter.kt");
                    }
                }
            }

            @Nested
            @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good")
            @TestDataPath("$PROJECT_ROOT")
            public class Good extends AbstractFirDiagnosticWithStdLibTest {
                @Test
                public void testAllFilesPresentInGood() throws Exception {
                    KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                }

                @Nested
                @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace")
                @TestDataPath("$PROJECT_ROOT")
                public class CallsInPlace extends AbstractFirDiagnosticWithStdLibTest {
                    @Test
                    public void testAllFilesPresentInCallsInPlace() throws Exception {
                        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                    }

                    @Test
                    @TestMetadata("atLeastOnce.kt")
                    public void testAtLeastOnce() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/atLeastOnce.kt");
                    }

                    @Test
                    @TestMetadata("atMostOnce.kt")
                    public void testAtMostOnce() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/atMostOnce.kt");
                    }

                    @Test
                    @TestMetadata("contractsUsage.kt")
                    public void testContractsUsage() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/contractsUsage.kt");
                    }

                    @Test
                    @TestMetadata("exactlyOnce.kt")
                    public void testExactlyOnce() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/exactlyOnce.kt");
                    }

                    @Test
                    @TestMetadata("flow.kt")
                    public void testFlow() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/flow.kt");
                    }

                    @Test
                    @TestMetadata("inPlaceLambda.kt")
                    public void testInPlaceLambda() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/inPlaceLambda.kt");
                    }

                    @Test
                    @TestMetadata("simple.kt")
                    public void testSimple() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/simple.kt");
                    }

                    @Test
                    @TestMetadata("unknown.kt")
                    public void testUnknown() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/callsInPlace/unknown.kt");
                    }
                }

                @Nested
                @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies")
                @TestDataPath("$PROJECT_ROOT")
                public class ReturnsImplies extends AbstractFirDiagnosticWithStdLibTest {
                    @Test
                    public void testAllFilesPresentInReturnsImplies() throws Exception {
                        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                    }

                    @Test
                    @TestMetadata("booleanOperators.kt")
                    public void testBooleanOperators() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/booleanOperators.kt");
                    }

                    @Test
                    @TestMetadata("conditionLogic.kt")
                    public void testConditionLogic() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/conditionLogic.kt");
                    }

                    @Test
                    @TestMetadata("eqNotEq.kt")
                    public void testEqNotEq() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/eqNotEq.kt");
                    }

                    @Test
                    @TestMetadata("inapplicable.kt")
                    public void testInapplicable() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/inapplicable.kt");
                    }

                    @Test
                    @TestMetadata("namedArguments.kt")
                    public void testNamedArguments() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/namedArguments.kt");
                    }

                    @Test
                    @TestMetadata("notNull.kt")
                    public void testNotNull() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/notNull.kt");
                    }

                    @Test
                    @TestMetadata("propertyAccessors.kt")
                    public void testPropertyAccessors() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/propertyAccessors.kt");
                    }

                    @Test
                    @TestMetadata("receivers.kt")
                    public void testReceivers() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/receivers.kt");
                    }

                    @Test
                    @TestMetadata("safeCall.kt")
                    public void testSafeCall() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/safeCall.kt");
                    }

                    @Test
                    @TestMetadata("trickyCases.kt")
                    public void testTrickyCases() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/trickyCases.kt");
                    }

                    @Test
                    @TestMetadata("typePredicate.kt")
                    public void testTypePredicate() throws Exception {
                        runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/returnsImplies/typePredicate.kt");
                    }
                }

                @Nested
                @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/variousContracts")
                @TestDataPath("$PROJECT_ROOT")
                public class VariousContracts extends AbstractFirDiagnosticWithStdLibTest {
                    @Test
                    public void testAllFilesPresentInVariousContracts() throws Exception {
                        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/variousContracts"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                    }

                    @Nested
                    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/variousContracts/newSyntax")
                    @TestDataPath("$PROJECT_ROOT")
                    public class NewSyntax extends AbstractFirDiagnosticWithStdLibTest {
                        @Test
                        public void testAllFilesPresentInNewSyntax() throws Exception {
                            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/variousContracts/newSyntax"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
                        }

                        @Test
                        @TestMetadata("functionsWithContract.kt")
                        public void testFunctionsWithContract() throws Exception {
                            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/good/variousContracts/newSyntax/functionsWithContract.kt");
                        }
                    }
                }
            }
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates")
    @TestDataPath("$PROJECT_ROOT")
    public class Delegates extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInDelegates() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("anonymousInDelegate.kt")
        public void testAnonymousInDelegate() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates/anonymousInDelegate.kt");
        }

        @Test
        @TestMetadata("delegateTypeMismatch.kt")
        public void testDelegateTypeMismatch() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates/delegateTypeMismatch.kt");
        }

        @Test
        @TestMetadata("delegateWithAnonymousObject.kt")
        public void testDelegateWithAnonymousObject() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates/delegateWithAnonymousObject.kt");
        }

        @Test
        @TestMetadata("propertyWithFunctionalType.kt")
        public void testPropertyWithFunctionalType() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates/propertyWithFunctionalType.kt");
        }

        @Test
        @TestMetadata("simpleDelegateProvider.kt")
        public void testSimpleDelegateProvider() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates/simpleDelegateProvider.kt");
        }

        @Test
        @TestMetadata("simpleDelegatedToMap.kt")
        public void testSimpleDelegatedToMap() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/delegates/simpleDelegatedToMap.kt");
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference")
    @TestDataPath("$PROJECT_ROOT")
    public class Inference extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInInference() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("builderInference.kt")
        public void testBuilderInference() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference/builderInference.kt");
        }

        @Test
        @TestMetadata("builderInferenceAndCoercionToUnit.kt")
        public void testBuilderInferenceAndCoercionToUnit() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference/builderInferenceAndCoercionToUnit.kt");
        }

        @Test
        @TestMetadata("builderInferenceFromStdlib.kt")
        public void testBuilderInferenceFromStdlib() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference/builderInferenceFromStdlib.kt");
        }

        @Test
        @TestMetadata("complexConstraintSystem.kt")
        public void testComplexConstraintSystem() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference/complexConstraintSystem.kt");
        }

        @Test
        @TestMetadata("flexibleTypeInSystem.kt")
        public void testFlexibleTypeInSystem() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference/flexibleTypeInSystem.kt");
        }

        @Test
        @TestMetadata("ifElvisReturn.kt")
        public void testIfElvisReturn() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference/ifElvisReturn.kt");
        }

        @Test
        @TestMetadata("plusAssignWithLambdaInRhs.kt")
        public void testPlusAssignWithLambdaInRhs() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/inference/plusAssignWithLambdaInRhs.kt");
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/initialization")
    @TestDataPath("$PROJECT_ROOT")
    public class Initialization extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInInitialization() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/initialization"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("fromLocalMembers.kt")
        public void testFromLocalMembers() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/initialization/fromLocalMembers.kt");
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k")
    @TestDataPath("$PROJECT_ROOT")
    public class J_k extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInJ_k() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("BasicWithAnnotatedJava.kt")
        public void testBasicWithAnnotatedJava() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/BasicWithAnnotatedJava.kt");
        }

        @Test
        @TestMetadata("BasicWithAnnotatedOverriddenJava.kt")
        public void testBasicWithAnnotatedOverriddenJava() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/BasicWithAnnotatedOverriddenJava.kt");
        }

        @Test
        @TestMetadata("BasicWithJava.kt")
        public void testBasicWithJava() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/BasicWithJava.kt");
        }

        @Test
        @TestMetadata("BasicWithJavaFakeOverride.kt")
        public void testBasicWithJavaFakeOverride() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/BasicWithJavaFakeOverride.kt");
        }

        @Test
        @TestMetadata("BasicWithPrimitiveJava.kt")
        public void testBasicWithPrimitiveJava() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/BasicWithPrimitiveJava.kt");
        }

        @Test
        @TestMetadata("capturedFlexible.kt")
        public void testCapturedFlexible() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/capturedFlexible.kt");
        }

        @Test
        @TestMetadata("complexFlexibleInference.kt")
        public void testComplexFlexibleInference() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/complexFlexibleInference.kt");
        }

        @Test
        @TestMetadata("FieldAccessFromDerived.kt")
        public void testFieldAccessFromDerived() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/FieldAccessFromDerived.kt");
        }

        @Test
        @TestMetadata("FieldAndGetter.kt")
        public void testFieldAndGetter() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/FieldAndGetter.kt");
        }

        @Test
        @TestMetadata("fieldOverride.kt")
        public void testFieldOverride() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/fieldOverride.kt");
        }

        @Test
        @TestMetadata("FieldSubstitution.kt")
        public void testFieldSubstitution() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/FieldSubstitution.kt");
        }

        @Test
        @TestMetadata("FlexiblePrimitiveOverloading.kt")
        public void testFlexiblePrimitiveOverloading() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/FlexiblePrimitiveOverloading.kt");
        }

        @Test
        @TestMetadata("flexibleTypeAliases.kt")
        public void testFlexibleTypeAliases() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/flexibleTypeAliases.kt");
        }

        @Test
        @TestMetadata("FunctionTypeInJava.kt")
        public void testFunctionTypeInJava() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/FunctionTypeInJava.kt");
        }

        @Test
        @TestMetadata("IntersectionTypesProblem.kt")
        public void testIntersectionTypesProblem() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/IntersectionTypesProblem.kt");
        }

        @Test
        @TestMetadata("JavaGetPrefixConflict.kt")
        public void testJavaGetPrefixConflict() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/JavaGetPrefixConflict.kt");
        }

        @Test
        @TestMetadata("JavaInheritsKotlinDerived.kt")
        public void testJavaInheritsKotlinDerived() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/JavaInheritsKotlinDerived.kt");
        }

        @Test
        @TestMetadata("JavaInheritsKotlinExtension.kt")
        public void testJavaInheritsKotlinExtension() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/JavaInheritsKotlinExtension.kt");
        }

        @Test
        @TestMetadata("JavaInheritsKotlinProperty.kt")
        public void testJavaInheritsKotlinProperty() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/JavaInheritsKotlinProperty.kt");
        }

        @Test
        @TestMetadata("JavaInheritsRawKotlin.kt")
        public void testJavaInheritsRawKotlin() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/JavaInheritsRawKotlin.kt");
        }

        @Test
        @TestMetadata("JavaSyntheticProperty.kt")
        public void testJavaSyntheticProperty() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/JavaSyntheticProperty.kt");
        }

        @Test
        @TestMetadata("JavaVisibility2.kt")
        public void testJavaVisibility2() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/JavaVisibility2.kt");
        }

        @Test
        @TestMetadata("KJKComplexHierarchy.kt")
        public void testKJKComplexHierarchy() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/KJKComplexHierarchy.kt");
        }

        @Test
        @TestMetadata("KJKComplexHierarchyWithNested.kt")
        public void testKJKComplexHierarchyWithNested() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/KJKComplexHierarchyWithNested.kt");
        }

        @Test
        @TestMetadata("KJKInheritance.kt")
        public void testKJKInheritance() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/KJKInheritance.kt");
        }

        @Test
        @TestMetadata("KJKInheritanceGeneric.kt")
        public void testKJKInheritanceGeneric() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/KJKInheritanceGeneric.kt");
        }

        @Test
        @TestMetadata("KotlinClassParameter.kt")
        public void testKotlinClassParameter() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/KotlinClassParameter.kt");
        }

        @Test
        @TestMetadata("KotlinClassParameterGeneric.kt")
        public void testKotlinClassParameterGeneric() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/KotlinClassParameterGeneric.kt");
        }

        @Test
        @TestMetadata("kt39076.kt")
        public void testKt39076() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/kt39076.kt");
        }

        @Test
        @TestMetadata("LoggerInstance.kt")
        public void testLoggerInstance() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/LoggerInstance.kt");
        }

        @Test
        @TestMetadata("MapCompute.kt")
        public void testMapCompute() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/MapCompute.kt");
        }

        @Test
        @TestMetadata("MapEntry.kt")
        public void testMapEntry() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/MapEntry.kt");
        }

        @Test
        @TestMetadata("mapMerge.kt")
        public void testMapMerge() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/mapMerge.kt");
        }

        @Test
        @TestMetadata("MyException.kt")
        public void testMyException() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/MyException.kt");
        }

        @Test
        @TestMetadata("MyIterable.kt")
        public void testMyIterable() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/MyIterable.kt");
        }

        @Test
        @TestMetadata("MyMap.kt")
        public void testMyMap() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/MyMap.kt");
        }

        @Test
        @TestMetadata("outerInnerClasses.kt")
        public void testOuterInnerClasses() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/outerInnerClasses.kt");
        }

        @Test
        @TestMetadata("OverrideWithJava.kt")
        public void testOverrideWithJava() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/OverrideWithJava.kt");
        }

        @Test
        @TestMetadata("RawType.kt")
        public void testRawType() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/RawType.kt");
        }

        @Test
        @TestMetadata("serializableString.kt")
        public void testSerializableString() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/serializableString.kt");
        }

        @Test
        @TestMetadata("smartSet.kt")
        public void testSmartSet() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/smartSet.kt");
        }

        @Test
        @TestMetadata("StaticClassConstructorFromBaseClass.kt")
        public void testStaticClassConstructorFromBaseClass() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/StaticClassConstructorFromBaseClass.kt");
        }

        @Test
        @TestMetadata("StaticFromBaseClass.kt")
        public void testStaticFromBaseClass() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/StaticFromBaseClass.kt");
        }

        @Test
        @TestMetadata("StaticGenericMethod.kt")
        public void testStaticGenericMethod() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/StaticGenericMethod.kt");
        }

        @Test
        @TestMetadata("SyntheticAfterFiltering.kt")
        public void testSyntheticAfterFiltering() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/SyntheticAfterFiltering.kt");
        }

        @Test
        @TestMetadata("SyntheticWithForEach.kt")
        public void testSyntheticWithForEach() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/SyntheticWithForEach.kt");
        }

        @Test
        @TestMetadata("typeParameterUse.kt")
        public void testTypeParameterUse() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/j+k/typeParameterUse.kt");
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/multiModule")
    @TestDataPath("$PROJECT_ROOT")
    public class MultiModule extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInMultiModule() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/multiModule"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("Basic.kt")
        public void testBasic() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/multiModule/Basic.kt");
        }

        @Test
        @TestMetadata("FakeOverrides.kt")
        public void testFakeOverrides() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/multiModule/FakeOverrides.kt");
        }

        @Test
        @TestMetadata("MemberType.kt")
        public void testMemberType() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/multiModule/MemberType.kt");
        }

        @Test
        @TestMetadata("Members.kt")
        public void testMembers() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/multiModule/Members.kt");
        }

        @Test
        @TestMetadata("SuperTypes.kt")
        public void testSuperTypes() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/multiModule/SuperTypes.kt");
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems")
    @TestDataPath("$PROJECT_ROOT")
    public class Problems extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInProblems() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("DeepCopyIrTree.kt")
        public void testDeepCopyIrTree() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/DeepCopyIrTree.kt");
        }

        @Test
        @TestMetadata("EnumMapGet.kt")
        public void testEnumMapGet() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/EnumMapGet.kt");
        }

        @Test
        @TestMetadata("invokePriority.kt")
        public void testInvokePriority() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/invokePriority.kt");
        }

        @Test
        @TestMetadata("invokePriorityComplex.kt")
        public void testInvokePriorityComplex() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/invokePriorityComplex.kt");
        }

        @Test
        @TestMetadata("KJKComplexHierarchyNestedLoop.kt")
        public void testKJKComplexHierarchyNestedLoop() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/KJKComplexHierarchyNestedLoop.kt");
        }

        @Test
        @TestMetadata("qualifierPriority.kt")
        public void testQualifierPriority() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/qualifierPriority.kt");
        }

        @Test
        @TestMetadata("receiverResolutionInLambda.kt")
        public void testReceiverResolutionInLambda() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/receiverResolutionInLambda.kt");
        }

        @Test
        @TestMetadata("weakHashMap.kt")
        public void testWeakHashMap() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/problems/weakHashMap.kt");
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/reinitializations")
    @TestDataPath("$PROJECT_ROOT")
    public class Reinitializations extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInReinitializations() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/reinitializations"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("constructorVarWrite.kt")
        public void testConstructorVarWrite() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/reinitializations/constructorVarWrite.kt");
        }
    }

    @Nested
    @TestMetadata("compiler/fir/analysis-tests/testData/resolveWithStdlib/smartcasts")
    @TestDataPath("$PROJECT_ROOT")
    public class Smartcasts extends AbstractFirDiagnosticWithStdLibTest {
        @Test
        public void testAllFilesPresentInSmartcasts() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/fir/analysis-tests/testData/resolveWithStdlib/smartcasts"), Pattern.compile("^([^.]+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("tryWithLambdaInside.kt")
        public void testTryWithLambdaInside() throws Exception {
            runTest("compiler/fir/analysis-tests/testData/resolveWithStdlib/smartcasts/tryWithLambdaInside.kt");
        }
    }
}
